/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./**/*.{js,ts,jsx,tsx}",
    "!./node_modules/**/*",
    "!./dist/**/*",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "surface-container-highest": "#dce2f7",
        "primary-fixed-dim": "#80d5cb",
        "on-secondary-fixed": "#00201e",
        "surface-tint": "#006a63",
        "on-primary-container": "#a3faef",
        "on-background": "#141b2b",
        "inverse-surface": "#293040",
        "primary-fixed": "#9cf2e8",
        "tertiary": "#694d00",
        "on-tertiary-container": "#ffe8be",
        "on-primary-fixed-variant": "#00504a",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "inverse-primary": "#80d5cb",
        "tertiary-container": "#876400",
        "surface-dim": "#d3daef",
        "on-tertiary-fixed-variant": "#5c4300",
        "on-tertiary-fixed": "#261a00",
        "background": "#f9f9ff",
        "surface-container-high": "#e1e8fd",
        "on-primary-fixed": "#00201d",
        "surface-container-low": "#f1f3ff",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "surface-container": "#e9edff",
        "tertiary-fixed-dim": "#f6be39",
        "on-primary": "#ffffff",
        "secondary-container": "#a8ece5",
        "inverse-on-surface": "#edf0ff",
        "on-surface-variant": "#3e4947",
        "secondary-fixed-dim": "#8fd3cc",
        "tertiary-fixed": "#ffdfa0",
        "on-surface": "#141b2b",
        "surface": "#f9f9ff",
        "secondary-fixed": "#abefe8",
        "surface-bright": "#f9f9ff",
        "on-error-container": "#93000a",
        "outline": "#6e7977",
        "on-secondary-container": "#266d68",
        "primary": "#005c55",
        "outline-variant": "#bdc9c6",
        "on-secondary-fixed-variant": "#00504b",
        "primary-container": "#0f766e",
        "secondary": "#216963",
        "surface-variant": "#dce2f7"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "48px",
        "gutter": "24px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        "base": "4px",
        "xs": "4px",
        "lg": "24px",
        "sm": "8px",
        "md": "16px"
      },
      fontSize: {
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["30px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-xl-mobile": ["32px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
